services:
  postgres:
    image: postgres:15
    container_name: remix_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remixdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
